[package]
name = "component"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/component.rs"

[dependencies]
gpui.workspace = true
lazy_static = "1.5.0"
linkme.workspace = true
once_cell = "1.20.3"
collections.workspace = true
parking_lot.workspace = true

[features]
default = []
